---
# Almost all linters; some of them are optional.

run:
  modules-download-mode: readonly
  issues-exit-code: 0

linters-settings:
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
    ignore-enum-members: ""
    package-scope-only: false
  godot:
    scope: toplevel
    exclude:
      - go-sumtype:decl
      - check interfaces
    capital: true
  godox:
    keywords:
      - HACK
  goimports:
    local-prefixes: github.com/FerretDB/dance
  gosimple:
    go: "1.18"
    checks: ["all"]
  govet:
    check-shadowing: true
    enable-all: true
    disable-all: false
  lll:
    line-length: 130
    tab-width: 1
  misspell:
    locale: US
    ignore-words:
      - guiness # present in the test dataset
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    allow-no-explanation: []
    require-explanation: true
    require-specific: true
  revive:
    enable-all-rules: true # FIXME does not actually work?
    ignore-generated-header: true
    severity: warning
    # rules:
    #   - name: exported
  staticcheck:
    go: "1.18"
    checks: ["all"]
  stylecheck:
    go: "1.18"
    checks: ["all"]
    dot-import-whitelist: []
    initialisms: []
    http-status-code-whitelist: []
  unparam:
    check-exported: true
  unused:
    go: "1.18"
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable-all: true
  disable:
    # TODO configure and enable one by one
    - cyclop
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustivestruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - goerr113
    - gomnd
    - gosec
    - ifshort
    - ireturn
    - nakedret
    - thelper
    - unparam
    - varnamelen
    - wrapcheck

    # TODO enable when goanalysis_metalinter supports generics
    - gosimple
    - staticcheck
    - stylecheck
    - unused

    - golint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nlreturn # too annoying
    - scopelint # deprecated
    - testpackage # we test internals
    - wsl # too annoying

issues:
  exclude-use-default: false

  exclude-rules:
    - path: internal/gotest/testjson.go
      linters:
        - tagliatelle
