---
version: '3.8'

services:
  ferretdb:
    image: ${FERRETDB_IMAGE:-ghcr.io/ferretdb/ferretdb:local}
    container_name: dance_ferretdb
    ports:
      - 127.0.0.1:27017:27017
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      # Always UTC+05:45. Set to catch timezone problems.
      - TZ=Asia/Kathmandu

  postgres:
    image: postgres:14.1
    container_name: dance_postgres
    ports:
      - 127.0.0.1:5432:5432
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      # UTC−03:30/−02:30. Set to catch timezone problems.
      - TZ=America/St_Johns
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=dance
